
mysportsfeeds:
  feed_names:
    - seasonal_games  # CORE
    - daily_games  # CORE
    - weekly_games  # CORE
    - current_season  # CORE
    - latest_updates  # CORE
    - seasonal_venues  # CORE
    - daily_player_gamelogs  # STATS
    - weekly_player_gamelogs  # STATS
    - seasonal_player_gamelogs  # STATS
    - daily_team_gamelogs  # STATS
    - weekly_team_gamelogs  # STATS
    - seasonal_team_gamelogs  # STATS
    - seasonal_team_stats  # STATS
    - seasonal_player_stats  # STATS
    - seasonal_standings  # STATS
    - daily_dfs  # DFS
    - weekly_dfs  # DFS
    - seasonal_dfs  # DFS
#    - seasonal_player_stats_projections  # PROJECTIONS
#    - daily_player_gamelogs_projections  # PROJECTIONS
#    - weekly_player_gamelogs_projections  # PROJECTIONS
#    - game_boxscore  # DETAILED
#    - game_playbyplay  # DETAILED
#    - game_lineup  # DETAILED
#    - player_injuries  # DETAILED
#    - players  # DETAILED
