version: '3.8'

# Local dev URL: http://127.0.0.1:9001
services:
  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - data-lake-network

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: metastore
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - data-lake-network

  hive-metastore:
    image: apache/hive:4.0.0-alpha-1
    container_name: hive-metastore
    environment:
      HIVE_METASTORE_USER: hive
      HIVE_METASTORE_PASSWORD: hive
      HIVE_METASTORE_DB_HOST: postgres
      HIVE_METASTORE_DB_TYPE: postgres
      HIVE_METASTORE_DB_DRIVER: org.postgresql.Driver
      SERVICE_NAME: metastore
    ports:
      - "9083:9083"
    depends_on:
      - postgres
    volumes:
      - hive_metastore_data:/data
    networks:
      - data-lake-network

  trino:
    image: trinodb/trino
    container_name: trino
    ports:
      - "8080:8080"
    depends_on:
      - hive-metastore
    volumes:
      - trino_data:/data
    networks:
      - data-lake-network

  # TODO: Add service for Plotly Dash app
#  dash:
#    build:
#      context: ./dash
#      dockerfile: Dockerfile
#    container_name: dash
#    ports:
#      - "8050:8050"
#    depends_on:
#      - trino
#    networks:
#      - data-lake-network

# TODO: Add service for Prefect server (if needed)
# Prefect Local Dev URL: http://0.0.0.0:4200
# set up prefect python client to use this service: (venv)>> prefect config set PREFECT_API_URL=http://localhost:4200/api
  prefect:
    image: prefecthq/prefect:3-python3.11
    container_name: prefect-server
    ports:
      - "4200:4200"
    command: >
      bash -c "prefect server start
      --host 0.0.0.0
      --port 4200"
    environment:
      - PREFECT_UI_URL=http://localhost:4200
      - PREFECT_API_URL=http://localhost:4200/api
    volumes:
      - prefect_data:/root/.prefect
    networks:
      - data-lake-network


volumes:
  minio_data:
  postgres_data:
  hive_metastore_data:
  trino_data:
  prefect_data:

networks:
  data-lake-network:

# TODO: Add any additional services or configurations as needed